- CHANGELOG.md
- lib/lighthouseProvider/LighthouseDevice.dart
- lib/lighthouseProvider/LighthouseProvider.dart
- lib/lighthouseProvider/widgets/LighthouseWidget.dart
- lib/main.dart
- lib/pages/MainPage.dart
Fixed the powerstate connection staying open.
Resolved #1
> #1 close connection on refresh

- CHANGELOG.md
- README.md
- android/app/src/main/kotlin/com/jeroen1602/lighthouse_pm/MainActivity.kt
- lib/pages/AboutPage.dart
- lib/pages/MainPage.dart
- lib/pages/PrivacyPage.dart
- pubspec.lock
- pubspec.yaml
- Added side drawer.
- Added About page.
- Added button to launch build-in licenses page.
- Added privacy page.
Resolves #2
> #2 add about page

- CHANGELOG.md
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/kotlin/com/jeroen1602/lighthouse_pm/MainActivity.kt
- lib/main.dart
- lib/pages/MainPage.dart
- lib/permissionsHelper/BLEPermissionsHelper.dart
- lib/widgets/EnableBluetoothAlertWidget.dart
- pubspec.lock
Converted the main activity to the Flutter 2 version.
(Android) added option to enable Bluetooth from the Bluetooth not enabled screen.
closese #4
> Created Bluetooth not enabled screen.

- CHANGELOG.md
- android/app/src/main/res/drawable/ic_launcher_background.xml
- pubspec.yaml
Added missing splash screen resource.
closes #24
> Fixed app crash on launch.

- CHANGELOG.md
- android/app/src/main/kotlin/com/jeroen1602/lighthouse_pm/MainActivity.kt
- lib/dialogs/EnableBluetoothDialogFlow.dart
- lib/dialogs/LocationPermissonDialogFlow.dart
- lib/lighthouseProvider/LighthouseDevice.dart
- lib/lighthouseProvider/LighthouseProvider.dart
- lib/main.dart
- lib/pages/AboutPage.dart
- lib/pages/MainPage.dart
- lib/pages/TroubleshootingPage.dart
- lib/permissionsHelper/BLEPermissionsHelper.dart
Made the troubleshooting page also show up after a scan with 0 found devices.
Updated the changelog.
Cleaned up some code.
closes #28
> Added a troubleshooting page.

- CHANGELOG.md
- lib/dialogs/EnableBluetoothDialogFlow.dart
- lib/dialogs/LocationPermissonDialogFlow.dart
- lib/lighthouseProvider/LighthouseDevice.dart
- lib/lighthouseProvider/widgets/LighthouseWidget.dart
- lib/pages/AboutPage.dart
- lib/pages/MainPage.dart
- lib/pages/PrivacyPage.dart
- lib/pages/TroubleshootingPage.dart
- lib/permissionsHelper/BLEPermissionsHelper.dart
- lib/widgets/EnableBluetoothAlertWidget.dart
- lib/widgets/PermanentPermissionDeniedAlertWidget.dart
- lib/widgets/PermissionsAlertWidget.dart
- pubspec.lock
- pubspec.yaml
> Add more troubleshooting tips

- CHANGELOG.md
- lib/lighthouseProvider/LighthouseDevice.dart
- pubspec.lock
- pubspec.yaml
Added mutex to state write.
closes #36
> Changed boolean mutex to actual mutex.

- lib/lighthouseProvider/LighthouseDevice.dart
- lib/lighthouseProvider/LighthousePowerState.dart
- lib/lighthouseProvider/devices/LighthouseV2Device.dart
- lib/lighthouseProvider/widgets/LighthouseWidget.dart
- lib/lighthouseProvider/widgets/UnknownStateAlertWidget.dart
> Renamed standby to sleep

- lib/lighthouseProvider/widgets/UnknownStateAlertWidget.dart
- lib/pages/SettingsPage.dart
- lib/widgets/ClearLastSeenAlertWidget.dart
- lib/widgets/EnableBluetoothAlertWidget.dart
- lib/widgets/PermanentPermissionDeniedAlertWidget.dart
- lib/widgets/PermissionsAlertWidget.dart
Changed all dialog `FlatButtons` to `SimpleDialogOption`s
> Added a dialog before clearing the last seen devices table.

- CHANGELOG.md
- lib/lighthouseProvider/LighthouseDevice.dart
- lib/lighthouseProvider/deviceExtensions/DeviceExtensions.dart
- lib/lighthouseProvider/deviceExtensions/DeviceWithExtensions.dart
- lib/lighthouseProvider/deviceExtensions/IdentifyDeviceExtension.dart
- lib/lighthouseProvider/devices/LighthouseV2Device.dart
- lib/lighthouseProvider/widgets/LighthouseMetadataPage.dart
> Add extra actions to metadata

- CHANGELOG.md
- lib/main.dart
- lib/pages/MainPage.dart
simply by adding a darkTheme: ThemeData.dark() to the MaterialApp init function.
i'll post some screenshots of darkmode here:
> user System theme for dark mode

- lib/lighthouseProvider/widgets/ViveBaseStationExtraInfoAlertWidget.dart
- lib/widgets/NicknameAlertWidget.dart
> Made sure the negative and positive options are the same for dialogs

- CHANGELOG.md
- lib/bloc.dart
- lib/data/local/MainPageSettings.dart
- lib/pages/MainPage.dart
- lib/pages/SettingsPage.dart
- lib/widgets/DropdownMenuListTile.dart
> Added option to change scan duration.

- lib/lighthouseProvider/LighthouseProvider.dart
- lib/lighthouseProvider/backend/FakeBLEBackend.dart
- lib/lighthouseProvider/backend/FlutterBlueLighthouseBackend.dart
- lib/lighthouseProvider/backend/LighthouseBackend.dart
- lib/pages/MainPage.dart
isScanning is now part of the back end instead of using the Flutter blue's version globally.
closes #54.
> Made isScanning part of the back end.

- CHANGELOG.md
- lib/bloc.dart
- lib/main.dart
- lib/pages/SettingsPage.dart
- pubspec.lock
- pubspec.yaml
> Added an option for selecting the preferred theme

- CHANGELOG.md
- lib/lighthouseProvider/widgets/UnknownStateAlertWidget.dart
- lib/lighthouseProvider/widgets/ViveBaseStationExtraInfoAlertWidget.dart
- lib/pages/MainPage.dart
- lib/widgets/NicknameAlertWidget.dart
- lib/widgets/PermanentPermissionDeniedAlertWidget.dart
- lib/widgets/PermissionsAlertWidget.dart
> Fixed dialog text color.

- CHANGELOG.md
- lib/lighthouseProvider/devices/ViveBaseStationDevice.dart
> Reverted Vive Base station power state back to UNKNOWN

- CHANGELOG.md
- lib/lighthouseProvider/widgets/LighthouseWidget.dart
- lib/main.dart
- lib/pages/HelpPage.dart
> Added a help page with some basic features that may be hidden.

- CHANGELOG.md
- lib/lighthouseProvider/widgets/LighthouseWidget.dart
- lib/pages/HelpPage.dart
I've decided to open the metadata page by a click instead of holding the power buttons. This is done because the metadata page is  important and most people don't know how to open it.
Holding the power button still works.
> Open metadata by click

- README.md
Added The F-Droid badge to the readme.
Closes #88
> Add get it on F-Droid

- CHANGELOG.md
- lib/lighthouseProvider/widgets/UnknownStateAlertWidget.dart
- lib/lighthouseProvider/widgets/ViveBaseStationExtraInfoAlertWidget.dart
- lib/widgets/ClearLastSeenAlertWidget.dart
- lib/widgets/DaoSimpleChangeStringAlertWidget.dart
- lib/widgets/EnableBluetoothAlertWidget.dart
- lib/widgets/NicknameAlertWidget.dart
- lib/widgets/PermanentPermissionDeniedAlertWidget.dart
- lib/widgets/PermissionsAlertWidget.dart
Fixed button order for UnknownStateAlertWidget.
Fixed button order for ViveBastStationExtraInfoAlertWidget.
Fixed button order for ClearLastSeenAlertWidget.
Fixed button order for DaoSimpleChangeStringAlertWidget.
Fixed button order for EnableBluetoothAlertWidget.
Fixed button order for NicknameAlertWidget.
Fixed button order for PermanentPermissionDeniedAlertWidget.
Fixed button order for PermissionAlertWidget.
closes #96
> Standardized dialog button order.

- ios/Runner/Info.plist
xCode will refuse to build without this key.
> Added missing bluetooth permission request key 

- CHANGELOG.md
- lib/data/dao/SettingsDao.dart
- lib/main.dart
- lib/pages/DatabaseTestPage.dart
- lib/pages/HelpPage.dart
- lib/pages/MainPage.dart
- lib/pages/SettingsPage.dart
- lib/pages/TroubleshootingPage.dart
- lib/pages/database/GroupDaoPage.dart
- lib/pages/database/NicknameDaoPage.dart
- lib/pages/database/SettingsDaoPage.dart
- lib/pages/database/ViveBaseStationDaoPage.dart
- lib/pages/settings/LHLicensePage.dart
- lib/pages/settings/PrivacyPage.dart
- lib/pages/settings/SettingsNicknamesPage.dart
- lib/pages/settings/SettingsViveBaseStationIdsPage.dart
- lib/widgets/ContentContainerWidget.dart
- Fixed the urls not working.
- Updated CHANGELOG.md.
- Added url for License.
> Added content scaling for web pages.

- CHANGELOG.md
- lib/main.dart
- lib/pages/NotFoundPage.dart
- lib/widgets/ContentContainerWidget.dart
Page only works for web or in debug mode.
closes #109
> 109 add 404 page

- CHANGELOG.md
- lib/lighthouseProvider/adapterState/AdapterState.dart
- lib/lighthouseProvider/backEnd/FlutterWebBluetoothBackEnd.dart
- lib/pages/MainPage.dart
- pubspec.lock
- pubspec.yaml
Fixed current state not showing up correctly.
closes #110
>  Added more info to the Bluetooth adapter unavailable.

- lib/pages/settings/PrivacyPage.dart
> Update privacy page

- CHANGELOG.md
- lib/data/Database.dart
- lib/data/dao/GroupDao.dart
- lib/data/dao/NicknameDao.dart
- lib/data/dao/ViveBaseStationDao.dart
- lib/data/tables/GroupTable.dart
- lib/data/tables/LastSeenDevicesTable.dart
- lib/data/tables/NicknameTable.dart
- lib/data/tables/ViveBaseStationIdTable.dart
- lib/lighthouseProvider/LighthouseProvider.dart
- lib/lighthouseProvider/backEnd/FlutterBlueLighthouseBackEndIO.dart
- lib/lighthouseProvider/deviceExtensions/ClearIdExtension.dart
- lib/lighthouseProvider/devices/ViveBaseStationDevice.dart
- lib/lighthouseProvider/widgets/LighthouseGroupWidget.dart
- lib/lighthouseProvider/widgets/LighthouseMetadataPage.dart
- lib/lighthouseProvider/widgets/OfflineLighthouseWidget.dart
- lib/lighthouseProvider/widgets/ViveBaseStationExtraInfoAlertWidget.dart
- lib/pages/MainPage.dart
- lib/pages/SettingsPage.dart
- lib/pages/database/GroupDaoPage.dart
- lib/pages/database/NicknameDaoPage.dart
- lib/pages/database/ViveBaseStationDaoPage.dart
- lib/pages/settings/SettingsNicknamesPage.dart
- lib/pages/settings/SettingsViveBaseStationIdsPage.dart
- lib/pages/shortcut/states/GetDeviceStream.dart
- lib/widgets/NicknameAlertWidget.dart
- pubspec.lock
- pubspec.yaml
> Cannot add 10 base stations   will n

- CHANGELOG.md
- lib/lighthouseProvider/backEnd/fake/FakeBluetoothDevice.dart
- lib/lighthouseProvider/backEnd/fake/FakeDeviceIdentifier.dart
- lib/lighthouseProvider/ble/DeviceIdentifier.dart
- lib/lighthouseProvider/helpers/FlutterBlueExtensions.dart
- lib/lighthouseProvider/widgets/LighthouseGroupWidget.dart
- lib/pages/settings/SettingsNicknamesPage.dart
- lib/pages/settings/SettingsViveBaseStationIdsPage.dart
- test/lighthouseProvider/backEnd/fake/FakeDeviceIdentifier_test.dart
Added fake device identifier generator for different platform (testing only).
Removed toUpperCase form identifiers as this will cause problems for web identifiers which are case sensitive.
Added tests for the new fake device identifier generator.
closes #116
> Fixed lighthouses showing in the group and blow the group for web.

- lib/platformSpecific/mobile/android/androidLauncherShortcut/io.dart
- lib/platformSpecific/mobile/android/androidLauncherShortcut/shared.dart
- lib/platformSpecific/mobile/android/androidLauncherShortcut/unsupported.dart
- test/lighthouseProvider/deviceExtensions/ShortcutExtension_test.dart
- test/platformSpecific/mobile/android/AndroidLaunchShortcut_test.dart
Fixed tests for ShortcutExtension to test the right thing.
> Added tests for AndroidLauncherShortcut.

- .github/workflows/tests.yaml
- CHANGELOG.md
- android/app/build.gradle
- android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
- android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- lib/color_schemes.dart
- lib/data/dao/settings_dao.dart
- lib/data/local/app_style.dart
- lib/data/local/theme_data_and_app_style_stream.dart
- lib/lighthouse_provider/widgets/lighthouse_metadata_page.dart
- lib/lighthouse_provider/widgets/lighthouse_power_button_widget.dart
- lib/lighthouse_provider/widgets/widget_for_extension.dart
- lib/main.dart
- lib/pages/base_page.dart
- lib/pages/database/settings_dao_page.dart
- lib/pages/main_page.dart
- lib/pages/material_test_page.dart
- lib/pages/settings/settings_nicknames_page.dart
- lib/pages/settings/settings_vive_base_station_ids_page.dart
- lib/pages/settings_page.dart
- lib/theming.dart
- lib/widgets/main_page_drawer.dart
- lib/widgets/material/selectable_app_bar.dart
- lib/widgets/material/selectable_list_tile.dart
- lighthouse_provider/lighthouse_back_end/lib/src/ble/bluetooth_characteristic.dart
- pubspec.lock
- pubspec.yaml
- Created a selectable app bar to extract the selection code into a single widget.
- Update to use material 3. (not all widgets have been updated yet)
- Added material test page for looking at all the colors in a single page.
- Updated default material colors.
- Added dynamic colors icon for Android 13.
- Created a setting to use the dynamic colors. Defaults to `true` if supported Updated gradle.
> Added dynamic colors to the app

- lib/data/dao/settings_dao.dart
- lib/pages/troubleshooting_page.dart
- lib/permissions_helper/ble_permissions_helper.dart
- lib/widgets/permanent_permission_denied_alert_widget.dart
- lib/widgets/permissions_alert_widget.dart
- lighthouse_provider/lighthouse_back_end/pubspec.yaml
- lighthouse_provider/lighthouse_back_ends/bluez_back_end/pubspec.yaml
- lighthouse_provider/lighthouse_back_ends/fake_back_end/pubspec.yaml
- lighthouse_provider/lighthouse_back_ends/flutter_web_bluetooth_back_end/pubspec.yaml
- lighthouse_provider/lighthouse_logger/pubspec.yaml
- lighthouse_provider/lighthouse_provider/pubspec.yaml
- lighthouse_provider/lighthouse_providers/pubspec.yaml
- lighthouse_provider/lighthouse_test_helper/pubspec.yaml
- pubspec.lock
- pubspec.yaml
- test/data/dao/settings_dao_test.dart
- test/helpers/fake_device_info.dart
- test/lighthouse_provider/widgets/unknown_state_alert_widget_test.dart
- test/permission_helper/ble_permissions_helper_test.dart
Fixed tests for the updated dependencies.
> Updated dependencies

- assets/pages/privacy_v1.0_en.md
- assets/pages/privacy_v1.1_en.md
- lib/intl/ordinal.dart
- lib/pages/settings/privacy_page.dart
- lib/widgets/markdown/super_script_syntax.dart
- lib/widgets/privacy_page_segment.dart
- pubspec.lock
- pubspec.yaml
- test/pages/privacy_page_test.dart
- test/widgets/markdown/super_script_syntax_test.dart
- test/widgets/privacy_page_segment_test.dart
Using markdown makes it easier to add translations in the future and update the text as a whole if needed.
> Changed privacy page to use markdown.

- .github/dependabot.yml
Added gradle and github actions to the list.
> Fixed dependabot yml not being accepted (hopefully)

- android/app/src/main/kotlin/com/jeroen1602/lighthouse_pm/MainActivity.kt
- android/app/src/main/res/drawable/ic_launcher_white.xml
- android/app/src/main/res/values-night-v31/styles.xml
- android/app/src/main/res/values-night/colors.xml
- android/app/src/main/res/values/colors.xml
Stopped using deprecated API for enabling Bluetooth. Changed background color for new Android 12+ launcher. (Now it's just simple (almost) black and white)
> Small changes for Android.

- android/app/build.gradle
- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- Set java version to 11
- Enabled check for release builds again
- Upgrade the gradle version to 7.5
> Upgraded Android gradle to version 7.4.0

- .github/workflows/tests.yaml
- README.md
- lib/main.dart
- lighthouse_provider/lighthouse_back_end/pubspec.yaml
- lighthouse_provider/lighthouse_back_ends/bluez_back_end/pubspec.yaml
- lighthouse_provider/lighthouse_back_ends/fake_back_end/pubspec.yaml
- lighthouse_provider/lighthouse_back_ends/flutter_web_bluetooth_back_end/pubspec.yaml
- lighthouse_provider/lighthouse_logger/pubspec.yaml
- lighthouse_provider/lighthouse_provider/pubspec.yaml
- lighthouse_provider/lighthouse_providers/pubspec.yaml
- lighthouse_provider/lighthouse_test_helper/lib/src/fake_persistence.dart
- lighthouse_provider/lighthouse_test_helper/pubspec.yaml
- pubspec.lock
- pubspec.yaml
- test/data/migration_helpers/fake_migrator.dart
Updated readme for linux builds.
> Upgraded the drift database to `2.4.2`.

- CHANGELOG.md
- README.md
- fastlane/metadata/android/en-US/full_description.txt
- lib/data/dao/settings_dao.dart
- lib/data/helper_structures/lighthouse_providers.dart
- lib/data/local/main_page_settings.dart
- lib/lighthouse_provider/lighthouse_provider_start.dart
- lib/main.dart
- lib/pages/database/settings_dao_page.dart
- lib/pages/settings_page.dart
- lib/pages/troubleshooting_page.dart
- lib/widgets/vive_base_station_alert_widget.dart
- Updated CHANGELOG.md.
- Updated full_description.txt.
- Moved setup of the `lighthouseProvider` into. lighthouse_provider_start.dart.
- Removed setting to enable Vive base station support.
- Removed troubleshooting item for Vive base station support.
> Enabled Vive base stations by default

- .github/workflows/tests.yaml
- android/app/build.gradle
- android/app/proguard-rules.pro
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/kotlin/com/jeroen1602/lighthouse_pm/LighthousePMApplication.kt
- lib/lighthouse_provider/lighthouse_provider_start.dart
- lib/pages/main_page.dart
- lib/widgets/scanning_mixin.dart
- lighthouse_provider/lighthouse_back_ends/flutter_reactive_ble_back_end/.gitignore
- lighthouse_provider/lighthouse_back_ends/flutter_reactive_ble_back_end/.metadata
- lighthouse_provider/lighthouse_back_ends/flutter_reactive_ble_back_end/README.md
- lighthouse_provider/lighthouse_back_ends/flutter_reactive_ble_back_end/analysis_options.yaml
- lighthouse_provider/lighthouse_back_ends/flutter_reactive_ble_back_end/lib/flutter_reactive_ble_end.dart
- lighthouse_provider/lighthouse_back_ends/flutter_reactive_ble_back_end/lib/src/ble/flutter_reactive_ble_characteristic.dart
- lighthouse_provider/lighthouse_back_ends/flutter_reactive_ble_back_end/lib/src/ble/flutter_reactive_ble_device.dart
- lighthouse_provider/lighthouse_back_ends/flutter_reactive_ble_back_end/lib/src/ble/flutter_reactive_ble_service.dart
- lighthouse_provider/lighthouse_back_ends/flutter_reactive_ble_back_end/lib/src/flutter_reactive_ble_io.dart
- lighthouse_provider/lighthouse_back_ends/flutter_reactive_ble_back_end/lib/src/flutter_reactive_ble_unsupported.dart
- lighthouse_provider/lighthouse_back_ends/flutter_reactive_ble_back_end/pubspec.yaml
- lighthouse_provider/lighthouse_provider/lib/src/adapter_state/adapter_state.dart
- lighthouse_provider/lighthouse_provider/test/adapter_state/adapter_state_test.dart
- pubspec.lock
- pubspec.yaml
This back end is for Android and iOS and allows the project to drop `flutter_blue` which seems to not get any updates anymore.
> Add flutter reactive ble as a back end

- lib/data/helper_structures/with_timeout.dart
- lib/pages/settings_page.dart
- lib/theming.dart
- lib/widgets/dao_data_widget.dart
- lib/widgets/markdown/src/icon_syntax.dart
- lighthouse_provider/lighthouse_back_end/pubspec.yaml
- lighthouse_provider/lighthouse_back_ends/bluez_back_end/lib/src/bluez_back_end_io.dart
- lighthouse_provider/lighthouse_back_ends/bluez_back_end/pubspec.yaml
- lighthouse_provider/lighthouse_back_ends/fake_back_end/pubspec.yaml
- lighthouse_provider/lighthouse_back_ends/flutter_blue_plus_back_end/lib/src/flutter_blue_plus_back_end_io.dart
- lighthouse_provider/lighthouse_back_ends/flutter_blue_plus_back_end/pubspec.yaml
- lighthouse_provider/lighthouse_back_ends/flutter_web_bluetooth_back_end/pubspec.yaml
- lighthouse_provider/lighthouse_logger/pubspec.yaml
- lighthouse_provider/lighthouse_provider/pubspec.yaml
- lighthouse_provider/lighthouse_providers/pubspec.yaml
- lighthouse_provider/lighthouse_test_helper/pubspec.yaml
- pubspec.lock
- pubspec.yaml
- shared/shared_platform/pubspec.yaml
- test/helpers/fake_device_info.dart
Fixed lint warnings with the new flutter version.
> Updated dependencies.
